// This file contains platforms used by the drop-down menu.

export const gamingPlatforms: { label: string; value: string }[] = [
  { label: '3DO', value: '3DO' },
  { label: 'Atari Jaguar', value: 'Atari Jaguar' },
  { label: 'Epic Games Store', value: 'Epic Games Store' },
  { label: 'Game Boy', value: 'Game Boy' },
  { label: 'Game Boy Advance', value: 'Game Boy Advance' },
  { label: 'Game Boy Color', value: 'Game Boy Color' },
  { label: 'GOG.com', value: 'GOG.com' },
  { label: 'Neo Geo Pocket', value: 'Neo Geo Pocket' },
  { label: 'NES', value: 'NES' },
  { label: 'Nintendo 3DS', value: 'Nintendo 3DS' },
  { label: 'Nintendo 64', value: 'Nintendo 64' },
  { label: 'Nintendo DS', value: 'Nintendo DS' },
  { label: 'Nintendo GameCube', value: 'Nintendo GameCube' },
  { label: 'Nintendo Switch', value: 'Nintendo Switch' },
  { label: 'Nintendo Switch 2', value: 'Nintendo Switch 2' },
  { label: 'Nintendo Wii', value: 'Nintendo Wii' },
  { label: 'Nintendo Wii U', value: 'Nintendo Wii U' },
  { label: 'Philips CD-i', value: 'Philips CD-i' },
  { label: 'PlayStation 2', value: 'PlayStation 2' },
  { label: 'PlayStation 3', value: 'PlayStation 3' },
  { label: 'PlayStation 4', value: 'PlayStation 4' },
  { label: 'PlayStation 5', value: 'PlayStation 5' },
  { label: 'PlayStation Portable', value: 'PlayStation Portable' },
  { label: 'PlayStation Vita', value: 'PlayStation Vita' },
  { label: 'SNES', value: 'SNES' },
  { label: 'Sega Dreamcast', value: 'Sega Dreamcast' },
  { label: 'Sega Genesis', value: 'Sega Genesis' },
  { label: 'Sega Saturn', value: 'Sega Saturn' },
  { label: 'Sony PlayStation', value: 'Sony PlayStation' },
  { label: 'Steam', value: 'Steam' },
  { label: 'WonderSwan', value: 'WonderSwan' },
  { label: 'Xbox', value: 'Xbox' },
  { label: 'Xbox 360', value: 'Xbox 360' },
  { label: 'Xbox One', value: 'Xbox One' },
  { label: 'Xbox Series X/S', value: 'Xbox Series X/S' },
];
